# Generated by Django 5.0.6 on 2024-05-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('salt', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
