# Generated by Django 5.0.6 on 2024-05-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='salt',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
    ]
