# Generated by Django 5.0.6 on 2024-05-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_producto_carbs_alter_producto_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
